export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',

  UPDATE_PIC_REQUEST: 'UPDATE_PIC_REQUEST',
  UPDATE_PIC_FAILURE: 'UPDATE_PIC_FAILURE',
  UPDATE_PIC_SUCCESS: 'UPDATE_PIC_SUCCESS',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  UPDATE_PROFILE_REQUEST:'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS:'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE:'UPDATE_PROFILE_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
}

export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
  GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
  GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE'
}

export const cartConstants = {

  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',

  GET_CART_REQUEST: 'GET_CART_REQUEST',
  GET_CART_SUCCESS: 'GET_CART_SUCCESS',
  GET_CART_FAILURE: 'GET_CART_FAILURE',

  RESET_CART_SUCCESS: 'RESET_CART_SUCCESS'
}

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
  GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
  GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE',

  // PRODUCT_FILTER_REQUEST: 'PRODUCT_FILTER_REQUEST',
  // PRODUCT_FILTER_SUCCESS: 'PRODUCT_FILTER_SUCCESS',
  // PRODUCT_FILTER_FAILURE: 'PRODUCT_FILTER_FAILURE',

  GET_PRODUCT_BY_CAT_SLUG_REQUEST: 'GET_PRODUCT_BY_CAT_SLUG_REQUEST',
  GET_PRODUCT_BY_CAT_SLUG_SUCCESS: 'GET_PRODUCT_BY_CAT_SLUG_SUCCESS',
  GET_PRODUCT_BY_CAT_SLUG_FAILURE: 'GET_PRODUCT_BY_CAT_SLUG_FAILURE',

  GET_PRODUCT_DETAIL_BY_ID_REQUEST: 'GET_PRODUCT_DETAIL_BY_ID_REQUEST',
  GET_PRODUCT_DETAIL_BY_ID_SUCCESS: 'GET_PRODUCT_DETAIL_BY_ID_SUCCESS',
  GET_PRODUCT_DETAIL_BY_ID_FAILURE: 'GET_PRODUCT_DETAIL_BY_ID_FAILURE'
}

export const addressConstants = {
  GET_ADDRESS_REQUEST: 'GET_ADDRESS_REQUEST',
  GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
  GET_ADDRESS_FAILURE: 'GET_ADDRESS_FAILURE',

  ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
  ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
  ADD_ADDRESS_FAILURE: 'ADD_ADDRESS_FAILURE',
}

export const orderConstants = {
  GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',

  GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST',
  GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FAILURE: 'GET_ORDERS_FAILURE',

  ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
  ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
  ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',
}

export const paymentConstants = {
  RAZORPAY_ORDER_REQUEST: 'RAZORPAY_ORDER_REQUEST',
  RAZORPAY_ORDER_SUCCESS: 'RAZORPAY_ORDER_SUCCESS',
  RAZORPAY_ORDER_FAILURE: 'RAZORPAY_ORDER_FAILURE',
}



